### ISSUE TITLE
Search_tmp tables fail

### ISSUE THREAD

**Issue by sylink** [magemojo/m2-ce-splitdb#11]
Some sites appear to use the built-in search for their category pages, in which case a search_tmp table is created.  Once enabling splitdb category pages fail with this report:

```{"0":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_9n2lhln4nc0.search_tmp_5abd35a84878a2_77903462' doesn't exist, query was: SELECT count(main_table.entity_id) AS `count`, MAX(min_price) AS `max`, MIN(min_price) AS `min`, STDDEV_SAMP(min_price) AS `std` FROM `catalog_product_index_price` AS `main_table` WHERE (main_table.entity_id in (select entity_id from search_tmp_5abd35a84878a2_77903462)) AND (customer_group_id = 0) AND (main_table.website_id = '1')","1":"#0 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Statement\/Pdo\/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)\n#1 \/srv\/public_html\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)\n#2 \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php(736): Zend_Db_Statement->execute(Array)\n#3 \/srv\/public_html\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Abstract.php(756): MageMojo\\SplitDb\\Adapter\\Pdo\\Mysql->query('SELECT count(ma...', Array)\n#4 \/srv\/public_html\/vendor\/magento\/module-catalog-search\/Model\/Adapter\/Mysql\/Dynamic\/DataProvider.php(118): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\\Framework\\DB\\Select))\n#5 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Dynamic\/Algorithm\/Auto.php(82): Magento\\CatalogSearch\\Model\\Adapter\\Mysql\\Dynamic\\DataProvider->getAggregations(Object(Magento\\Framework\\Search\\Dynamic\\EntityStorage))\n#6 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Dynamic\/Algorithm\/Auto.php(63): Magento\\Framework\\Search\\Dynamic\\Algorithm\\Auto->getMaxPriceInt(Object(Magento\\Framework\\Search\\Dynamic\\EntityStorage))\n#7 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Dynamic\/Algorithm\/Auto.php(47): Magento\\Framework\\Search\\Dynamic\\Algorithm\\Auto->getRange(Object(Magento\\Framework\\Search\\Request\\Aggregation\\DynamicBucket), Array, Object(Magento\\Framework\\Search\\Dynamic\\EntityStorage))\n#8 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Adapter\/Mysql\/Aggregation\/Builder\/Dynamic.php(50): Magento\\Framework\\Search\\Dynamic\\Algorithm\\Auto->getItems(Object(Magento\\Framework\\Search\\Request\\Aggregation\\DynamicBucket), Array, Object(Magento\\Framework\\Search\\Dynamic\\EntityStorage))\n#9 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Adapter\/Mysql\/Aggregation\/Builder.php(97): Magento\\Framework\\Search\\Adapter\\Mysql\\Aggregation\\Builder\\Dynamic->build(Object(Magento\\CatalogSearch\\Model\\Adapter\\Mysql\\Aggregation\\DataProvider\\Interceptor), Array, Object(Magento\\Framework\\Search\\Request\\Aggregation\\DynamicBucket), Object(Magento\\Framework\\DB\\Ddl\\Table))\n#10 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Adapter\/Mysql\/Aggregation\/Builder.php(76): Magento\\Framework\\Search\\Adapter\\Mysql\\Aggregation\\Builder->processAggregations(Object(Magento\\Framework\\Search\\Request), Object(Magento\\Framework\\DB\\Ddl\\Table), Array)\n#11 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Adapter\/Mysql\/Adapter.php(84): Magento\\Framework\\Search\\Adapter\\Mysql\\Aggregation\\Builder->build(Object(Magento\\Framework\\Search\\Request), Object(Magento\\Framework\\DB\\Ddl\\Table), Array)\n#12 \/srv\/public_html\/vendor\/magento\/module-search\/Model\/SearchEngine.php(42): Magento\\Framework\\Search\\Adapter\\Mysql\\Adapter->query(Object(Magento\\Framework\\Search\\Request))\n#13 \/srv\/public_html\/vendor\/magento\/framework\/Search\/Search.php(72): Magento\\Search\\Model\\SearchEngine->search(Object(Magento\\Framework\\Search\\Request))\n#14 \/srv\/public_html\/vendor\/magento\/module-catalog-search\/Model\/ResourceModel\/Fulltext\/Collection.php(344): Magento\\Framework\\Search\\Search->search(Object(Magento\\Framework\\Api\\Search\\SearchCriteria))\n#15 \/srv\/public_html\/vendor\/magento\/framework\/Data\/Collection\/AbstractDb.php(340): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFiltersBefore()\n#16 \/srv\/public_html\/vendor\/magento\/module-catalog-search\/Model\/ResourceModel\/Fulltext\/Collection.php(386): Magento\\Framework\\Data\\Collection\\AbstractDb->_renderFilters()\n#17 \/srv\/public_html\/vendor\/magento\/module-eav\/Model\/Entity\/Collection\/AbstractCollection.php(909): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFilters()\n#18 \/srv\/public_html\/vendor\/magento\/module-catalog\/Model\/ResourceModel\/Product\/Collection.php(749): Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->load(false, false)\n#19 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection->load(false, false)\n#20 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callParent('load', Array)\n#21 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#22 \/srv\/public_html\/generated\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection\/Interceptor.php(26): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callPlugins('load', Array, Array)\n#23 \/srv\/public_html\/vendor\/magento\/module-review\/Observer\/CatalogBlockProductCollectionBeforeToHtmlObserver.php(38): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->load()\n#24 \/srv\/public_html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(72): Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#25 \/srv\/public_html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver), Object(Magento\\Framework\\Event\\Observer))\n#26 \/srv\/public_html\/vendor\/magento\/framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#27 \/srv\/public_html\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('catalog_block_p...', Array)\n#28 \/srv\/public_html\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(395): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('catalog_block_p...', Array)\n#29 \/srv\/public_html\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(107): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()\n#30 \/srv\/public_html\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(268): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\n#31 \/srv\/public_html\/vendor\/magento\/module-page-cache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n#32 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\\n<script>\\n    t...')\n#33 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#34 \/srv\/public_html\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(39): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#35 \/srv\/public_html\/vendor\/magento\/framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#36 \/srv\/public_html\/vendor\/magento\/framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#37 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#38 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#39 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#40 \/srv\/public_html\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(26): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#41 \/srv\/public_html\/vendor\/magento\/framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#42 \/srv\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#43 \/srv\/public_html\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#44 {main}","url":"\/us\/outerwear.html","script_name":"\/index.php"}```

**Comment by rafaelstz** [comment]
Hi @sylink ,
I was able to simulate it, then I did some changes and I merged this PR https://github.com/magemojo/m2-ce-splitdb/pull/13 . If the issue persists please let me know your M2 version and how could I simulate the issue.

**Comment by sylink** [comment]
Looks like this still occurs, set up a default M2 install with the small performance profile - http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-perf-data.html then go to a category page -

{"0":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_570tmvfsoqb.search_tmp_5ac782c2d83aa8_26588826' doesn't exist, query was: SELECT `search_tmp_5ac782c2d83aa8_26588826`.`entity_id`, `search_tmp_5ac782c2d83aa8_26588826`.`score` FROM `search_tmp_5ac782c2d83aa8_26588826`","1":"#0 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Statement\/Pdo\/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)\n#1 \/srv\/public_html\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)\n#2 \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php(772): Zend_Db_Statement->execute(Array)\n#3 \/srv\/public_html\/vendor\/magento\/zendframework1\/library\/Zend\

Same as https://570tmvfsoqbjcp4e.mojostratus.io/category-1/category-1-1.html

**Comment by rafaelstz** [comment]
I was able to simulate, then I provided this PR to fix it https://github.com/magemojo/m2-ce-splitdb/pull/14
