### ISSUE TITLE
Issue using setup:upgrade

### ISSUE THREAD

**Issue by rafaelstz** [magemojo/m2-ce-splitdb#2]
This is the issue using `setup:upgrade`:

![Magento 2 CLI setup upgrade](https://user-images.githubusercontent.com/610598/36694871-62da3894-1b1e-11e8-9197-9fb4469e68da.png)

**Comment by rafaelstz** [comment]
It's working with this test:

![image](https://user-images.githubusercontent.com/610598/36917551-e163358e-1e35-11e8-8f80-afa3a3aefb31.png)

**Comment by gnuzealot** [comment]
I updated both of these files to return true as indicated. 

./vendor/magento/magento2-base/setup/src/Magento/Setup/Validator/DbValidator.php
./setup/src/Magento/Setup/Validator/DbValidator.php

Without the change I get the privilege error as expected. After changing the files to return true I'm getting a different error. It's much further along in the process.

root@sshd-canarylarge-xyz:/srv/public_html# php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/srv/public_html/generated/code/Composer
/srv/public_html/generated/code/Magento
/srv/public_html/generated/code/Symfony
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_AdminNotification':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Backup':
Module 'Magento_Eav':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Payment':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Sales':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Bundle':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Checkout':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_UrlRewrite':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'MageMojo_SplitDb':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_Paypal':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_SampleData':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Shopial_Facebook':
Schema post-updates:
Module 'Magento_Store':
Module 'Magento_AdminNotification':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Backup':
Module 'Magento_Eav':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Running schema recurring...
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Running schema recurring...
Module 'Magento_Rule':
Module 'Magento_Payment':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Sales':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Running schema recurring...
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Checkout':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Running schema recurring...
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_UrlRewrite':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Running schema recurring...SQLSTATE[HY000]: General error: 1290 The MySQL server is running with the --read-only option so it cannot execute this statement, query was: UPDATE `integration` SET `setup_type` = ? WHERE (integration_id='1')

**Comment by gnuzealot** [comment]
Still getting an error on setup:upgrade

Running schema recurring...Sorry, something went wrong granting permissions. You can find out more in the exceptions log.

Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /srv/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3864 in /srv/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', '/srv/public_htm...', 3864, Array)
#1 /srv/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(3864): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in /srv/public_html/vendor/magento/framework/App/ErrorHandler.php on line 61


Exception log shows:
[2018-03-07 01:47:08] main.CRITICAL: There is no active transaction {"exception":"[object] (PDOException(code: 0): There is no active transaction at /srv/public_html/app/code/MageMojo/SplitDb/Adapter/Pdo/Mysql.php:394)"} []

**Comment by ericvhileman** [comment]
@rafaelstz I tried installing but get the error:

Running schema recurring...SQLSTATE[HY000]: General error: 1290 The MySQL server is running with the --read-only option so it cannot execute this statement, query was: UPDATE `integration` SET `setup_type` = ? WHERE (integration_id='75')

I have **NOT** modified the files:
./vendor/magento/magento2-base/setup/src/Magento/Setup/Validator/DbValidator.php
./setup/src/Magento/Setup/Validator/DbValidator.php

Full output:
www-data@servicepod-759fcf85b7-pqkq7:~/public_html$ bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/srv/public_html/generated/code/Composer
/srv/public_html/generated/code/Magento
/srv/public_html/generated/code/Symfony
The directory '/srv/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_AdminNotification':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Backup':
Module 'Magento_Eav':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Payment':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Sales':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Bundle':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Checkout':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_UrlRewrite':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'MageMojo_SplitDb':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_Paypal':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_SampleData':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Shopial_Facebook':
Schema post-updates:
Module 'Magento_Store':
Module 'Magento_AdminNotification':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Backup':
Module 'Magento_Eav':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Running schema recurring...
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Running schema recurring...
Module 'Magento_Rule':
Module 'Magento_Payment':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Sales':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Running schema recurring...
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Checkout':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Running schema recurring...
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_UrlRewrite':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
**Running schema recurring...SQLSTATE[HY000]: General error: 1290 The MySQL server is running with the --read-only option so it cannot execute this statement, query was: UPDATE `integration` SET `setup_type` = ? WHERE (integration_id='75')**

**Comment by ericvhileman** [comment]
I have modified the files:
./vendor/magento/magento2-base/setup/src/Magento/Setup/Validator/DbValidator.php
./setup/src/Magento/Setup/Validator/DbValidator.php

Still getting the error:
Running schema recurring...SQLSTATE[HY000]: General error: 1290 The MySQL server is running with the --read-only option so it cannot execute this statement, query was: UPDATE `integration` SET `setup_type` = ? WHERE (integration_id='75')

**Comment by ericvhileman** [comment]
On a fresh install.  No modifications to DbValidator.php files.

I changed both connections to go to writer.  I was able to install (setup:enable MageMojo_SplitDB) and run setup upgrade (setup:upgrade).

I changed the reader to the read only db.  I ran a load test.  Connections were going to reader.  That's good.

The remaining problem is that while installed, with env.php readonly going to reader, setup:upgrade cannot be run.

**Comment by rafaelstz** [comment]
Hi @ericvhileman, I've upgraded README file to have the right configuration, check if it's like this image below, I had had some issues locally when I used **readonly** instead of **readonly_setup**.

![image](https://user-images.githubusercontent.com/610598/37259992-aa9e3754-256c-11e8-811f-8dc86ee4e025.png)

**Comment by ericvhileman** [comment]
@rafaelstz Looks like I have that correct:

![image](https://user-images.githubusercontent.com/4987539/37260044-07142f50-2565-11e8-8e1b-7195d012b22c.png)

**Comment by rafaelstz** [comment]
Fixed on that PR below.
https://github.com/magemojo/m2-ce-splitdb/pull/10
